version: '2'

services:
  smile-backend: 
    build : ./Blood-bank-backend
    image : paulshauvik99/smile-backend:v2
    container_name: 'smile-backend'
    env_file:
      - config.env

  smile-frontend: 
    build : ./Blood-bank-frontend/smile
    image : paulshauvik99/smile-frontend:v2
    container_name: 'smile-frontend'
    depends_on :
      - smile-backend
    
  proxy:
    image: nginx:1.16.0-alpine
    container_name: 'smile-proxy'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command : certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email smileorg99@gmail.com --agree-tos --no-eff-email -d www.smileorganization.in smileorganization.in
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt



