
# services:
#   backend:
#     build: 
#       context: ./Blood-bank-backend
#     command: gunicorn smile.wsgi --bind 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     extra_hosts:
#       - "localhost:192.168.1.12"
#   frontend:
#     build:
#       context: ./Blood-bank-frontend/smile
#     extra_hosts:
#       - "localhost:192.168.1.12"
#     volumes:
#       - react_build:/app/dist
#   nginx:
#     image: nginx:1.16.0-alpine
#     ports:
#       - 80:8080
#     extra_hosts:
#       - "localhost:192.168.1.12"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#       - react_build:/var/www/react
#     depends_on:
#       - backend
#       - frontend
# volumes:
#   react_build:


version: '2'

services:
  smile-backend: 
    build : ./Blood-bank-backend
    image : paulshauvik99/smile-backend:v2
    container_name: 'smile-backend'
    environment : 
      - SECRET_KEY=django-secured-1i&!f7cipita@ep7%hvmq&e)x&(@(s1zq5t47%b=yifc62j+50
      - TWILIO_ACCOUNT_SID=AC77f125f317171f793ce6f7a414f0d5dc
      - TWILIO_AUTH_TOKEN=7a8d3a6a00f36b7e92d197823344c35a
      - TWILIO_PHONE_NUMBER=+14073260071
      - HOST=mongodb+srv://gdas:abcdefgh@smile1.lbmzkff.mongodb.net/?retryWrites=true&w=majority
      - USERNAME=gdas
      - PASSWORD=abcdefgh
      - AUTHSOURCE=admin

  smile-frontend: 
    build : ./Blood-bank-frontend/smile
    image : paulshauvik99/smile-frontend:v2
    container_name: 'smile-frontend'
    depends_on :
      - smile-backend
    
  proxy:
    build: ./nginx
    image: paulshauvik99/smile-proxy:v2
    container_name: 'smile-proxy'
    restart: always
    ports:
      - "80:80"



