version: '2'

services:
  smile-backend: 
    build : ./Blood-bank-backend
    image : gdas37467/smile-backend:v2
    container_name: 'smile-backend'
    ports:
      - "8000:8000"

  smile-frontend: 
    build : ./Blood-bank-frontend/smile
    image : gdas37467/smile-frontend:v2
    container_name: 'smile-frontend'
    ports:
      - "80:80"
      - "443:443"
    depends_on :
      - smile-backend
    
  # proxy:
  #   image: nginx:latest
  #   container_name: 'smile-proxy'
  #   restart: always
  #   ports:
  #     - "80:8080"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - react_build:/var/www/react
  #   depends_on:
  #     - smile-backend
  #     - smile-frontend

# volumes:
#   react_build: