# Generated by Django 4.1.13 on 2024-05-18 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('dob', models.DateField(null=True)),
                ('bloodGroup', models.CharField(default='', max_length=30)),
                ('phoneNumber', models.TextField(default='', max_length=14, null=True)),
                ('email', models.TextField(default='', max_length=30, null=True)),
                ('lastDonated', models.DateField(null=True)),
                ('address', models.TextField(default='', max_length=500, null=True)),
                ('registrationDate', models.DateField(null=True)),
                ('isThalassemia', models.BooleanField(default=False, null=True)),
                ('totalDonation', models.IntegerField(default=0)),
                ('loan', models.BooleanField(default=False)),
                ('gender', models.CharField(default='', max_length=300, null=True)),
                ('registeredByAdmin', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
